### ISSUE TITLE
ZEIT Nowによるレビュープロセスの改善

### ISSUE THREAD

**Issue by tnir** [django-ja/djangoproject.jp#15]
#8 でGitHub Pagesへ移行することを決めたが、PRのレビューを容易にするため、ZEIT Nowインテグレーション設定する。

**Comment by tnir** [comment]
ZEIT側でのOrgへのGitHub 設定完了 https://github.com/organizations/django-ja/settings/installations。

#14 で正しく設定できていることも確認。 #14 のマージまで想定している一貫したワークフローが確認できたら、クローズする。

**Comment by tnir** [comment]
もしかしたら、こちらの対応により #3 も実現できているかもしれない。

/cc @hirokiky

**Comment by hirokiky** [comment]
良いですね。おりをみてCloudFront移行しておきます。
