### ISSUE TITLE
画像リンク切れ: 翻訳プロジェクトへの参加方法

### ISSUE THREAD

**Issue by c-bata** [django-ja/djangoproject.jp#23]
「Transifexへのユーザー登録とDjangoドキュメント翻訳プロジェクトへの参加方法」のページにて画像のリンクが切れているようです。

<img width="1317" alt="ScreenShot 2020-05-01 4 26 38" src="https://user-images.githubusercontent.com/5564044/80751003-fcf29180-8b63-11ea-8610-b616c189430e.png">

https://djangoproject.jp/howtojoin-transifex/

**Comment by tnir** [comment]
ありがとうございます。

ローカルでやっても再現しなかったので、Vercel (旧ZEIT) の問題かもしれませんので、Vercel Supportに問い合わせました。 `Ticket (#51987) submitted.`

**Comment by tnir** [comment]
"-"始まりのファイル名/フォルダ名はアップロードされないというサポートの回答だったので、 #24 でソースを修正してマージし、（自動）デプロイしました。

@c-bata 今は正しく見えているかと思います。

- https://djangoproject.jp/howtojoin-transifex/
- https://djangoproject.jp/howtotranslate/

cc @hirokiky

**Comment by c-bata** [comment]
修正ありがとうございます！
