### ISSUE TITLE
miyadaiku移行

### ISSUE THREAD

**Issue by hirokiky** [django-ja/djangoproject.jp#6]
静的サイトジェネレーターに移行する

**Comment by masmatsum** [comment]
@hirokiky  昨年末に口頭でお話ししたことを確認させていただきたいのですが（記憶があいまいになってしまったため）、
今は、何かのCMS から出力したものをデプロイしているという話でしたかね？

**Comment by masmatsum** [comment]
@hirokiky さんから口頭で聞いたこと

* 諸々の事情で動的CMSは使えない
* いま master ブランチにおいてあるHTMLは、 mezzanine タグを打ったリビジョンから生成したもの
* 選定する静的サイトジェネレータに特に条件はない

**Comment by masmatsum** [comment]
Python 製なのでとりあえず Miyadaiku で行こうと思います

**Comment by hirokiky** [comment]
:+1: miyadaiku

**Comment by tnir** [comment]
fugoって書いてあったけど、実は[Hugo](https://gohugo.io/)だった？
