### ISSUE TITLE
GitHub Pagesへの移行

### ISSUE THREAD

**Issue by tnir** [django-ja/djangoproject.jp#8]
Amazon S3からGitHub Pagesへの移行を検討する。

**Comment by hirokiky** [comment]
移行は決定で。
CloudFront+ACMでホストします。

ビルド済みHTMLを `/docs` に入れるようにサイトのビルドする側 (Miyadaikuなど) で設定してほしい。

**Comment by tnir** [comment]
2年くらい進んでいないようなので #15 で対応したZEIT Nowでもいいかもですね。 https://djangoproject-jp.now.sh/ 
↑こちらに対してカスタムドメイン設定してやれば使えるはずだし、Miyadaiku化する場合 (#6) もカスタムコマンド実行できるので、対応可能かと。

/cc @hirokiky

**Comment by hirokiky** [comment]
移行しました。
